In [1]:
import numpy as np

In [3]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
sub_arr = arr[0:5]
sub_arr

array([1, 2, 3, 4, 5])

In [7]:
sub_arr[:] = 0
sub_arr

array([0, 0, 0, 0, 0])

In [8]:
arr

array([ 0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

### We need copy method

In [9]:
arr_copy = arr.copy()


In [11]:
arr_copy [:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [13]:
print(arr)
print(arr_copy)

[ 0  0  0  0  0  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100]
