In [1]:
import numpy as np

### Scalar element #
#### 0 dimentions

0 dimentions

In [4]:
scalar = np.array(42)
scalar.ndim

0

### Vector
#### 1 dimention

In [5]:
vector = np.array([1,2,3])
vector.ndim

1

### Matrix
#### 2 dimention

In [7]:
matrix = np.array([[1,2,3],[1,2,3],[1,2,3]])
matrix.ndim

2

### Tensor
#### 3 dimentions

In [9]:
tensor = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
tensor.ndim

3

## Add or delete dimentions

In [10]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [13]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [14]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Little challenge
* Make a 5 dimentions tensor
* Add 1 dimention
* Eliminate all unused dimentions

In [24]:
tensor5 = np.array([[[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]],[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]],[[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]],[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]]])
tensor5.ndim 

5

In [27]:
tensor5 = np.expand_dims(tensor5, axis=0)
tensor5.ndim

8

In [28]:
tensor5 = np.squeeze(tensor5)
tensor5.ndim

5